### ISSUE TITLE
create sensu docker image, lightweight using alpine linux

### ISSUE THREAD

**Issue by oryband** [sensu/sensu#1201]
I think it's high time sensu will provide a Docker image, for various reasons:

1. Easier to install in production.
1. Easier to develop using tools like docker-compose.
1. Not forced to use Ubuntu or CentOS

Rounds [have already created an image for this purpose](https://hub.docker.com/r/rounds/sensu). Perhaps we should PR?

**Comment by oryband** [comment]
At rounds we create private images which inherit from the public image above:

1. We copy in private RabbitMQ SSL keys to a `rounds/sensu-api` private image.
1. `rounds/sensu-client` image inherits from `rounds/sensu-api` and also copies our custom checks scripts (Python).
1. `rounds/sensu-server` sensu-server image also inherits from `sensu-api` and copies our subscription configuration.

In addition, we're using a `docker-compose.yml` for testing custom check scripts:
```yaml
version: "2"

services:
  client:
    build: client
    image: rounds/sensu-client
    command: client
    environment:
      - SENSU_LOG_LEVEL=debug
      # crash on rabbitmq connection failure
      - SENSU_TRANSPORT_RECONNECT_ON_ERROR=false

      - SENSU_CLIENT_SUBSCRIPTIONS="sub1,sub2,sub3"
    links:
      - api
      - rabbitmq

  server:
    build: server
    image: rounds/sensu-server
    command: server
    environment:
      - SENSU_LOG_LEVEL=debug
      - SENSU_TRANSPORT_RECONNECT_ON_ERROR=false
    links:
      - api
      - redis
      - rabbitmq

  api:
    build: api
    image: rounds/sensu-api
    command: api
    environment:
      - SENSU_LOG_LEVEL=debug
      - SENSU_TRANSPORT_RECONNECT_ON_ERROR=false
    links:
      - redis
      - rabbitmq

  uchiwa:
    build: uchiwa
    image: rounds/sensu-uchiwa
    environment:
      - UCHIWA_LOGLEVEL=debug
    ports:
      - "3000:3000"
    links:
      - api

  redis:
    # official trusted build doesn't support passing password at runtime
    image: bitnami/redis:3.0.7-1
    environment:
      - REDIS_PASSWORD=guest

  rabbitmq:
    build: rabbitmq
    # rabbitmq trusted build has bugs when using cert keys:
    # https://github.com/docker-library/rabbitmq/issues/66
    image: rounds/sensu-rabbitmq
    # ports:
    #   # management on ssl
    #   # requires adding ssl/client/keycert.p12 to your browser
    #   - "15671"
    hostname: rabbitmq-sensu
```
