### ISSUE TITLE
Investigate using RuboCop

### ISSUE THREAD

**Issue by portertech** [sensu/sensu#1538]
Check out https://github.com/fnichol/finstyle

**Comment by cwjohnston** [comment]
My concern with finstyle is that it is basically unmaintained at this point, and therefore stuck on an older RuboCop. This is good because the policies don't change, but also bad because bugs. Probably better to crib from it's default configuration at this point.

For reference, latest Rubocop (0.47.1) finds 3720 offenses in master. With the following configuration that number drops to 560:

``` yaml
Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
  Max: 55
Metrics/ClassLength:
  Max: 300
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 55
Metrics/ModuleLength:
  Max: 300
Style/StringLiterals:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: hash_rockets
Style/Proc:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/SpaceInsideHashLiteralBraces:
  Enabled: false
Style/IndentHash:
  Enabled: false
Style/AccessorMethodName:
  Enabled: false
Style/UnlessElse:
  Enabled: false
```

Thoughts?
