### ISSUE TITLE
no packages for Raspbian / Raspberry Pi

### ISSUE THREAD

**Issue by FlorinAndrei** [sensu/sensu#1676]
## Expected Behavior

I would expect to find Sensu packages somewhere, built for Raspbian.

## Current Behavior

Could not find such packages anywhere.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Sensu version used:
* Active Sensu extensions (e.g. WizardVan 0.1.0):
* Operating System and version (e.g. Ubuntu 14.04): Raspbian Jessie
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2):

**Comment by FlorinAndrei** [comment]
I would only need to run sensu-client on the Raspberry Pi. I run the server on Ubuntu.

**Comment by majormoses** [comment]
Did you try to install with the normal debian repo/package? Raspbian Jessie is just a custom debian if I am not mistaken so with a bit of tweaking (changing your codename to match a vanilla debian) it will likely work.

https://sensuapp.org/docs/0.28/platforms/sensu-on-ubuntu-debian.html#sensu-core

**Comment by FlorinAndrei** [comment]
I've added this repo:

```
deb https://sensu.global.ssl.fastly.net/apt jessie main
```

(I've actually tried both `main` and `unstable`)

Then I did `apt-get update`.

But then I get:

```
# apt-get install sensu
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package sensu
```

I looked at the repo files, and there are no packages in the `armhf` section, which explains the error message when I'm installing it.

The RPi is an ARM system, it's not AMD64, and apparently the Sensu packages are binary. :(

**Comment by majormoses** [comment]
ah makes sense, @portertech @cwjohnston any plans to support arm builds?

**Comment by portertech** [comment]
Unfortunately, our build pipeline, which runs on AWS EC2, does not currently support the arm architecture. We believe sensu-omnibus can successfully build arm packages, however, we have not yet automated the process.

We have an issue to experiment with QEMU https://github.com/sensu/sensu-omnibus/issues/82 Keep an eye on that issue for any progress (although low priority at this moment).

**Comment by FlorinAndrei** [comment]
There is a potential workaround: install Sensu as a gem. It's cumbersome and it's more work, etc. But I'll add it here just in case someone is desperate for some kind of solution, however imperfect.

Chunk of Ansible code:

```
  - name: install Sensu gem
    gem: name=sensu user_install=yes state=present version=0.29.0

  - name: create Sensu dirs
    file: path={{ item }} state=directory
    with_items:
    - /etc/sensu/conf.d
    - /etc/sensu/extensions
    - /var/log/sensu

  - name: configure Sensu
    template: src={{ item }} dest=/{{ item }} owner=root group=root mode=0644
    with_items:
    - etc/sensu/conf.d/client.json
    - etc/sensu/conf.d/transport.json
    - etc/sensu/conf.d/rabbitmq.json
    - etc/sensu/extensions/system-profile.rb
    - etc/sensu/conf.d/system_profile.json
    - etc/sensu/conf.d/extensions.json
```

The file templates are just what you would expect when configuring Sensu the usual way.

Missing from the above:

- a script to start/stop the service
- a logrotate script

I have yet to add these myself to the setup.
