### ISSUE TITLE
How to create a filter that also checks for history value?

### ISSUE THREAD

**Issue by pietervogelaar** [sensu/sensu#1749]
I have the following filter defined in Hiera:

```
sensu::filters:
  state_change_with_occurrences_critical:
    negate: false
    attributes:
      occurrences: "eval: value == 5 || (':::action:::' == 'resolve' && check['history'][-2] == 2)"
```

In Slack I only want to receive message about CRITICAL or OK sensu events.

With the filter above I would like to receive only a message with a state change after 5 occurrences or a message that a CRITICAL is OK again. But at the moment with `eval: value == 5 || ':::action:::' == 'resolve'` I also get a OK message after WARNING.

What would be the proper syntax to check the exit code of the previous check result? I figure the check['history'] syntax above is not correct yet.
