### ISSUE TITLE
Is it possible to increase the history in event data?

### ISSUE THREAD

**Issue by pietervogelaar** [sensu/sensu#1781]
At the moment the history array in event data contains the last 20 check exit codes. I my handler filter I do some logic based on the history to reduce noise to Slack.

```
  # The fifteenth occurrence after state change (role:windows 60th) or resolve after at least 15 times critical
  # Noise can be reduced for certain checks even more by setting the check.occurrences attribute larger than 15
  state_change_with_occurrences_critical:
    negate: false
    attributes:
      occurrences: "eval: (':::client.role:::' != 'windows' && value == :::check.occurrences|15:::) || (':::client.role:::' == 'windows' && value == :::check.occurrences|60:::) || ':::action:::' == 'resolve'"
      check:
        history: "eval: (value.last == '0' && value[-16...-1].uniq.length == 1 && value[-16...-1].uniq[0] == '2') || (value.last == '2' && value[-15...-1].uniq.length == 1 && value[-15...-1].uniq[0] == '2')"
```

But I like to have more than 20 history entries, let's say 100. Is that possible?
